// This file is automatically generated by build.rs

pub const CAN_SATSLINKER_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_SATSLINK_TOKEN_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_II_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 140, 4, 39, 16, 241, 21, 113, 65, 105, 138, 252, 102, 187, 226, 108, 52, 58, 174, 96, 167, 144, 189, 230, 10, 224, 67, 83, 158, 218, 254, 39, 192, 15, 221, 194, 13, 131, 128, 120, 90, 166, 167, 66, 30, 54, 50, 216, 64, 19, 186, 90, 49, 243, 159, 38, 88, 29, 89, 168, 149, 69, 86, 70, 136, 23, 234, 2, 183, 103, 83, 10, 211, 241, 200, 151, 138, 146, 142, 139, 151, 51, 7, 207, 211, 13, 199, 71, 164, 144, 85, 61, 24, 214, 3, 26, 96]";
pub const CAN_MODE: &'static str = "dev";
pub const CAN_IC_HOST: &'static str = "http://localhost:8080";
