// This file is automatically generated by build.rs

pub const CAN_SATSLINKER_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_SATSLINK_TOKEN_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_II_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 175, 59, 114, 243, 41, 27, 243, 136, 76, 43, 191, 238, 138, 169, 110, 84, 71, 22, 56, 137, 150, 131, 208, 97, 109, 133, 241, 101, 200, 221, 53, 68, 76, 231, 207, 139, 31, 170, 200, 254, 254, 105, 181, 103, 45, 179, 121, 178, 6, 127, 239, 54, 39, 209, 223, 210, 223, 14, 28, 185, 160, 193, 70, 249, 151, 55, 72, 153, 154, 109, 209, 150, 11, 166, 139, 213, 63, 245, 33, 4, 155, 240, 214, 146, 63, 85, 216, 18, 85, 110, 145, 218, 153, 211, 104, 245]";
pub const CAN_MODE: &'static str = "dev";
pub const CAN_IC_HOST: &'static str = "http://localhost:8080";
