// This file is automatically generated by build.rs

pub const CAN_SATSLINKER_CANISTER_ID: &'static str = "bkyz2-fmaaa-aaaaa-qaaaq-cai";
pub const CAN_SATSLINK_TOKEN_CANISTER_ID: &'static str = "bd3sg-teaaa-aaaaa-qaaba-cai";
pub const CAN_II_CANISTER_ID: &'static str = "be2us-64aaa-aaaaa-qaabq-cai";
pub const CAN_ROOT_KEY: &'static str = "[48, 129, 130, 48, 29, 6, 13, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 1, 2, 1, 6, 12, 43, 6, 1, 4, 1, 130, 220, 124, 5, 3, 2, 1, 3, 97, 0, 178, 3, 168, 33, 113, 188, 186, 148, 206, 112, 151, 117, 184, 242, 46, 77, 225, 139, 179, 136, 226, 10, 28, 198, 67, 239, 228, 243, 87, 74, 130, 189, 180, 233, 91, 128, 104, 35, 121, 180, 231, 5, 66, 165, 36, 169, 147, 239, 18, 69, 238, 139, 175, 135, 212, 41, 28, 145, 213, 45, 250, 167, 72, 107, 120, 87, 95, 0, 130, 130, 115, 133, 47, 89, 172, 169, 74, 30, 84, 87, 0, 13, 179, 59, 167, 119, 53, 17, 99, 227, 112, 11, 0, 30, 236, 142]";
pub const CAN_MODE: &'static str = "dev";
pub const CAN_IC_HOST: &'static str = "http://localhost:8080";
